name: Branch Name Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          if [[ ! "$BRANCH" =~ ^(main|master|development|dev|feature/|bugfix/|hotfix/) ]]; then
            echo "❌ Invalid branch name: $BRANCH"
            exit 1
          fi